codecov:
  notify:
    wait_for_ci: yes
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: off
      optimade:
        threshold: 1%
        flags:
          - project
      validator:
        threshold: 1%
        flags:
          - validator
    patch:
      default:
        threshold: 5%
    changes: off
