---
profile: PLACEHOLDER_PROFILE
email: aiida@localhost
first_name: AiiDA
last_name: OPTIMADE
institution: Materials-Consortia
db_backend: PLACEHOLDER_BACKEND
db_engine: postgresql_psycopg2
db_host: localhost
db_port: 5432
db_name: PLACEHOLDER_DATABASE_NAME
db_username: postgres
db_password: test
repository: PLACEHOLDER_REPOSITORY
broker_protocol: amqp
broker_username: guest
broker_password: guest
broker_host: 127.0.0.1
broker_port: 5672
broker_virtual_host: ''
