name: OPTiMaDe validator
description: Validate your OPTiMaDe server using the optimade-python-tools validator
author: Casper Welzel Andersen, Matthew Evans
branding:
  icon: server
  color: green

inputs:
  protocol:
    description: Protocol for the OPTiMaDe URL
    required: false
    default: http
  domain:
    description: Domain for the OPTiMaDe URL (defaults to the GH Actions runner host)
    required: false
    default: gh_actions_host
  port:
    description: Port for the OPTiMaDe URL
    required: false
  path:
    description: Path of the OPTiMaDe (versioned) base URL - MUST start with '/'
    required: false
    default: /v0
  all versioned paths:
    description: >
      Whether to test all possible versioned base URLs:
        /vMAJOR; /vMAJOR.MINOR; /vMAJOR.MINOR.PATCH
      If this is 'true', the input 'path' MUST exempt the version part (e.g., '/optimade' instead of '/optimade/v0').
      If this is 'false', the input 'path' MUST include the version part (e.g., '/optimade/v0' instead of '/optimade').
    required: false
    default: false
  index:
    description: Whether or not this is an index meta-database
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
